/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STAT_H_RPCGEN
#define _STAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXDATALEN 200

struct data {
	struct {
		u_int data_len;
		int *data_val;
	} data;
};
typedef struct data data;


#define STATPROG 21678
#define STATVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VARIANCE 1
extern  int * variance_1(data *, CLIENT *);
extern  int * variance_1_svc(data *, struct svc_req *);
#define AVERAGE 2
extern  int * average_1(data *, CLIENT *);
extern  int * average_1_svc(data *, struct svc_req *);
#define STDDEV 3
extern  int * stddev_1(data *, CLIENT *);
extern  int * stddev_1_svc(data *, struct svc_req *);
#define MAXIMUM 4
extern  int * maximum_1(data *, CLIENT *);
extern  int * maximum_1_svc(data *, struct svc_req *);
#define MINIMUM 5
extern  int * minimum_1(data *, CLIENT *);
extern  int * minimum_1_svc(data *, struct svc_req *);
extern int statprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VARIANCE 1
extern  int * variance_1();
extern  int * variance_1_svc();
#define AVERAGE 2
extern  int * average_1();
extern  int * average_1_svc();
#define STDDEV 3
extern  int * stddev_1();
extern  int * stddev_1_svc();
#define MAXIMUM 4
extern  int * maximum_1();
extern  int * maximum_1_svc();
#define MINIMUM 5
extern  int * minimum_1();
extern  int * minimum_1_svc();
extern int statprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STAT_H_RPCGEN */
